### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zhulik** [zhulik/gruby#2]
# TODO:
- [x] Add a Github workflow, libmruby.a must be cached
- [x] Configure dependabot
- [x] Change default branch to main
- [x] Rename package to gruby
- [x] Add CODEOWNERS
- [x] Add code of conduct
- [ ] Add Changelog
- [ ] Update readme
- [ ] Update docs
- [x] Import repository to terraform
  - [ ] Add branch protection
  - [x] Delete branch on PR merge
  - [x] Disable projects
  - [x] Disable wiki
- [x] Add golangci-lint
- [ ] Fix all suppressed with //nolint checks
- [x] Rewrite tests using gomega
  - [x] array_test.go
  - [x] context_test.go
  - [x] examples_test.go
  - [x] gc_test.go
  - [x] mruby_test.go
  - [x] value_test.go
  - [x] class_test.go
  - [x] decode_test.go
  - [x] func_test.go
  - [x] hash_test.go
  - [x] parser_test.go
